### ISSUE TITLE
Error encountered trying to run Contig extender

### ISSUE THREAD

**Issue by JustineCharon** [dengzac/contig-extender#2]
Hi, 

I am trying to run contig extender on my contigs assembled using MegaHit, using default parameters and Bowtie2 v2.4.1. 
I encounter the following error : 

> ValueError: Buffer dtype mismatch, expected 'long' but got 'double' 
(see below the corresponding log file). 

I have no idea what could be the reason for this...
Thanks in advance for your help !

Justine

```
Input and filter stats:
	Input sequences: 24,930,495
	Input bases: 3,307,495,007
	Input mean length: 132.67
	Good sequences: 24,250,132 (97.27%)
	Good bases: 3,207,524,479
	Good mean length: 132.27
	Bad sequences: 680,363 (2.73%)
	Bad bases: 99,970,528
	Bad mean length: 146.94
	Sequences filtered by specified parameters:
	lc_method: 680363
[156974] Failed to execute script extender_wrapper
/scratch/RDS-FSC-PlasmoVir-RW/PlasmoVir_2021/5_contigs_megahit/tmpkkmlb897
Namespace(branch_limit=1, complex_threshold=15, coverage=10, extend_tolerance=2.5, m1='/scratch/PlasmoVir/PlasmoVir_2021/4_Host_depletion/PcNZ.no_plasmodium.R1.fastq', m2='/scratch/PlasmoVir/PlasmoVir_2021/4_Host_depletion/PcNZ.no_plasmodium.R2.fastq', maxins=500, min_branch_score=5, min_overlap_length=15, out='/scratch/PlasmoVir/PlasmoVir_2021/5_contigs_megahit/PcNZ.contig_extended', pair_constraint=False, paired=False, reads='/scratch/RDS-FSC-PlasmoVir-RW/PlasmoVir_2021/5_contigs_megahit/tmpkkmlb897', reference='azE0MV8y', stop_length=250, threads='24')
Using bowtie2 at /usr/local/bowtie2/2.4.1/bowtie2
Temp dir: tmpqvddthn5
Using extend threshold 711
Extending /scratch/PlasmoVir/PlasmoVir_2021/5_contigs_megahit/PcNZ.contig_extended/tmpkkmlb897_azE0MV8y/0.fa
Traceback (most recent call last):
  File "extender_wrapper.py", line 173, in <module>
  File "extender/extender.pyx", line 658, in extender.run_script
  File "extender/extender.pyx", line 605, in extender._main
  File "extender/extender.pyx", line 281, in extender.iterate
ValueError: Buffer dtype mismatch, expected 'long' but got 'double'
CMD: touch /scratch/PlasmoVir/PlasmoVir_2021/5_contigs_megahit/PcNZ.contig_extended.fasta.bowtie2.started
CMD: bowtie2-build /scratch/PlasmoVir/PlasmoVir_2021/5_contigs_megahit/PcNZ.contig_extended.fasta /scratch/PlasmoVir/PlasmoVir_2021/5_contigs_megahit/PcNZ.contig_extended.fasta.bowtie2
Settings:
  Output files: "/scratch/PlasmoVir/PlasmoVir_2021/5_contigs_megahit/PcNZ.contig_extended.fasta.bowtie2.*.bt2"
  Line rate: 6 (line is 64 bytes)
  Lines per side: 1 (side is 64 bytes)
  Offset rate: 4 (one in 16)
  FTable chars: 10
  Strings: unpacked
  Max bucket size: default
  Max bucket size, sqrt multiplier: default
  Max bucket size, len divisor: 4
  Difference-cover sample period: 1024
  Endianness: little
  Actual local endianness: little
  Sanity checking: disabled
  Assertions: disabled
  Random seed: 0
  Sizeofs: void*:8, int:4, long:8, size_t:8
Input files DNA, FASTA:
  /scratch/PlasmoVir/PlasmoVir_2021/5_contigs_megahit/PcNZ.contig_extended.fasta
Error: could not open /scratch/PlasmoVir/PlasmoVir_2021/5_contigs_megahit/PcNZ.contig_extended.fasta
Total time for call to driver() for forward index: 00:00:00
Error: Encountered internal Bowtie 2 exception (#1)
Command: bowtie2-build --wrapper basic-0 /scratch/PlasmoVir/PlasmoVir_2021/5_contigs_megahit/PcNZ.contig_extended.fasta /scratch/PlasmoVir/PlasmoVir_2021/5_contigs_megahit/PcNZ.contig_extended.fasta.bowtie2 
Error, cmd: bowtie2-build /scratch/PlasmoVir/PlasmoVir_2021/5_contigs_megahit/PcNZ.contig_extended.fasta /scratch/PlasmoVir/PlasmoVir_2021/5_contigs_megahit/PcNZ.contig_extended.fasta.bowtie2 died with ret: 256 at /usr/local/trinity/2.5.1/util/align_and_estimate_abundance.pl line 778.
```

**Comment by sersancar** [comment]
I have encountered the same error trying to extend my viral contigs assembled using Spades. I case it could be useful, I attach the screen output:

**extender_wrapper spadesResults/blast/totalContigs.fasta --m1 /mnt/sdc1/Ordesa/trimResults/pairedReads_1.fastq --m2 /mnt/sdc1/Ordesa/trimResults/pairedReads_2.fastq --out extenderResults --enable-pair-constraint
/mnt/sdc1/Ordesa/tmpkrwfle_s
Namespace(branch_limit=1, complex_threshold=15, coverage=10, extend_tolerance=2.5, m1='/mnt/sdc1/Ordesa/trimResults/pairedReads_1.fastq', m2='/mnt/sdc1/Ordesa/trimResults/pairedReads_2.fastq', maxins=500, min_branch_score=5, min_overlap_length=15, out='extenderResults', pair_constraint=True, paired=True, reads='/mnt/sdc1/Ordesa/tmpkrwfle_s', reference='TWFyX05PREVfMV9sZW5ndGhfMTk1OTY4X2Nvdl8xNC45NTA5NTc=', stop_length=250, threads=24)
Using bowtie2 at /home/sersancar/anaconda3/bin/bowtie2
Running in paired mode
Temp dir: tmp4gu8y_zp
Input and filter stats:
	Input sequences: 17,410,666
	Input bases: 2,193,622,751
	Input mean length: 125.99
	Good sequences: 17,265,824 (99.17%)
	Good bases: 2,192,677,894
	Good mean length: 127.00
	Bad sequences: 144,842 (0.83%)
	Bad bases: 944,857
	Bad mean length: 6.52
	Sequences filtered by specified parameters:
	lc_method: 144842
Using extend threshold 702
Extending extenderResults/tmpkrwfle_s_TWFyX05PREVfMV9sZW5ndGhfMTk1OTY4X2Nvdl8xNC45NTA5NTc=/0.fa
Traceback (most recent call last):
  File "extender_wrapper.py", line 173, in <module>
  File "extender/extender.pyx", line 658, in extender.run_script
  File "extender/extender.pyx", line 605, in extender._main
  File "extender/extender.pyx", line 281, in extender.iterate
ValueError: Buffer dtype mismatch, expected 'long' but got 'double'
[2823034] Failed to execute script extender_wrapper**

Thanks in advance.
