### ISSUE TITLE
extender_wrapper not found

### ISSUE THREAD

**Issue by magadancito** [dengzac/contig-extender#4]
Hi dear dengzac, I had a problem with the run of extender_wrapper, I have  Ubuntu 18.04 and python 3.7. I install all libraries recommended and the distutils module and its impossible run the script, I attach the error message:

Traceback (most recent call last):
  File "extender_wrapper.py", line 16, in <module>
  File "extender/extender.pyx", line 19, in init extender
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils.version'
[5053] Failed to execute script extender_wrapper

**Comment by dengzac** [comment]
Are you running the precompiled binary at dist/extender_wrapper? It should include all needed libraries.
Also, does the import work if you run it in the python interpreter?

**Comment by Anna-pro** [comment]
Hello! I have the same issue:

@name_login dist]$ ./extender_wrapper -h
Traceback (most recent call last):
  File "extender_wrapper.py", line 16, in <module>
  File "extender/extender.pyx", line 19, in init extender
ModuleNotFoundError: No module named 'distutils'
[12091] Failed to execute script extender_wrapper

I was running from compiled folder "dist", use linux and python 3.7. I have installed it using the command: 
sh ./build.sh, which ends with "Build successful: output dist/extender_wrapper".
Just "./build.sh" didn't work due to this error:
-bash: ./build.sh: Permission denied

**Comment by xutaodeng** [comment]
Use the precompiled dist/extender_wrapper is the preferred way. It should include every required components

**Comment by SamMcGreig** [comment]
I am also getting the same issue as @Anna-pro. This issue persists with both the precompiled dist/extender_wrapper and one I built using the build.sh file. Running `from distutils.version import LooseVersion` in the python interpreter seems to work, so I am unsure what is causing this problem.

As an aside, is it possible to have this tool available as a conda package?

**Comment by xutaodeng** [comment]
This seems to be caused by a bug in PyInstaller: https://github.com/pyinstaller/pyinstaller/issues/4064
The tool is now distributed as a Docker container instead. Please pull the latest master branch and let me know if the issue persists.
I'll look into creating a conda package.
